services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/